### ISSUE TITLE
FLAVOR=xxx "is not exist!"

### ISSUE THREAD

**Issue by hurzl** [kdeguchi/pkg_replace#1]
When this error occurs pkg_replace exits instead of continuing with the next package.
Happens fo example with old py27 packages: "** FLAVOR=py27 is not exist!" 
and it doesn't even tell which package was the problem.

-> line 524 in get_pkgname_from_portdir

**Comment by kdeguchi** [comment]
Fix bug checking FLAVORS a5ab07a8c5fc1fc83d742e9b8eca57dea23ed646
