### ISSUE TITLE
Crash on removed ports

### ISSUE THREAD

**Issue by hurzl** [kdeguchi/pkg_replace#3]
for example:
```
** 'multimedia/librtmp' has removed from ports tree:
**     Has expired: Depends on legacy functionality of OpenSSL and superseded by multimedia/ffmpeg (2024-04-30)
** Skipping 'librtmp-2.4.20190330_1' - removed.
/usr/local/sbin/pkg_replace: arithmetic expression: variable not set: "cnt_removed+1"
```

**Comment by kdeguchi** [comment]
Thanks for your report.
I have fixed this bug in 7369ee14022bdf8bb78ec8a292130b963d1f40d9.

**Comment by kdeguchi** [comment]
Perhaps, the ports tree will be modified soon.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278823
Thank you.

**Comment by kdeguchi** [comment]
Bugfixed pkg_replace-20240507 is now reflected in the ports tree.
